INSERT INTO BOOK (ID,TITLE,DESCRIPTION,PRICE) VALUES(1,'SPRING RECEIPES','SPRING RECEIPES',199.0);
INSERT INTO BOOK (ID,TITLE,DESCRIPTION,PRICE) VALUES(2,'CLOUD COMPUTING','INTRODUCTION TO CLOUD COMPUTING',295.0);
